### ISSUE TITLE
change file directories

### ISSUE THREAD

**Issue by weixiong-zheng-berkeley** [SlaybaughLab/BART#20]
Change file directories s.t. 
1. source and header files are in the same folder
2. derived and base classes files are in the same folder
Is the point 2 as what we've concluded in lab meeting? @rachelslaybaugh 

This issue will be resolved after #4 .

**Comment by rachelslaybaugh** [comment]
Yes, 
we've resolved this in the lab meeting and recorded in the doc here https://github.com/SlaybaughLab/BART/blob/master/doc/initial-planning.md
