### ISSUE TITLE
Separate builder functionalities when rewriting the BARTDriver

### ISSUE THREAD

**Issue by victor-dr-z** [SlaybaughLab/BART#63]
Builder functions defined in BARTDriver make it too long to read, maintain and test.

Idea structure would be having builder functions in a separate class s.t. BARTDriver will be concise and will only call builders without defining them. Attempts trying implementing this structure failed with unindentified templating errors at the early stage of dev branch.

As we are rewriting the whole thing, it is the perfect time to first implementing those builder functions in a separate class `BARTBuilder<dim>` as member methods and then migrating `BARTDriver<dim>`. Preliminary attempt in the [personal new branch](https://github.com/weixiong-zheng-berkeley/BART/tree/new-driver) is very encourage as unit testing passed.

This is part of #54 . Unit tests based on CTest will be implemented as well. Once PR #60 gets merged, GTest tests will be developed accordingly.

**Comment by jsrehak** [comment]
All bart builder factory functions were moved to the base classes.
