### ISSUE TITLE
Need to add debug and release modes in CMakeLists

### ISSUE THREAD

**Issue by jsrehak** [SlaybaughLab/BART#73]
The `debug` and `release` modes of compilation need to be added to CMakeLists. I'm not sure all the differences we want between the two, so we should probably use this thread to discuss that.

Testing is the first thing I can think of, the testing executable and compiler flags for coverage and gtest should these only be included when building `debug`?

Is there a difference between `debug` and, say, `development`? What are your thoughts @weixiong-zheng-berkeley

**Comment by weixiong-zheng-berkeley** [comment]
We don’t have need for doing this now. But let me explain why we want them sometimes.

Debug mode is namely used for debug. GDB or LLVM can be used with such a mode to find errors like Segmentation violation.

Release mode, namely, is made when the code is ready to be used in computations. It can be as several times faster than debug mode.

The reason I found this was when doing crest, it by default now thinks we are doing test for both modes yet we haven’t even made executable in release mode. So u can see testing failures. I suspect if might be changing setting of auto pilot or you manually changed the build type macro.

**Comment by jsrehak** [comment]
I know the difference between `debug` and `release`.

My question is: when do we want to build the tests? Should we build them with `debug` or make a specific `development` build mode that has zero optimization like `debug`, but also builds tests?
