### ISSUE TITLE
Reflective BC error

### ISSUE THREAD

**Issue by victor-dr-z** [SlaybaughLab/BART#79]
Issue #9 came up as `num_initial_cells%num_process!=0`. In the investigation, it is revealed that the real issue is about the reflective BC as when we turn the reflective BC off, the solution will always be consistently correct however many number of processors are used.

So #9 is closed and turned into this issue.

**Comment by weixiong-zheng-berkeley** [comment]
Not sure if it's about AQ data implementation or just the special way of even parity implementation.

**Comment by weixiong-zheng-berkeley** [comment]
The even parity implementation is based on [Noh](https://www.osti.gov/servlets/purl/10167247). In serial mode, the solution is always correct. Yet, when parallelizing the calculations with distributed triangulations, the solution could be inconsistent. There would be a chance that this BC is not compatible with how the parallel computation is enabled using Lagrangian multiplier.

I guess one trivial way to see is once we have SAAF or FO implemented, we'll check if the reflective BC is correct in parallel mode.
