### ISSUE TITLE
Move MaterialProperties to restart with Google Style

### ISSUE THREAD

**Issue by victor-dr-z** [SlaybaughLab/BART#85]
@AlexanderBlank This is the first thing to do along with #37 using Google test. #16 is closed so don't worry about 

I will generate a patch for the header file and you only need to work on source file.

The task itself may require you to read [google style](https://google.github.io/styleguide/cppguide.html). Also, minimal [Gtest](https://github.com/google/googletest/blob/master/googletest/docs/Primer.md) is necessary. Take a look at examples I and @jsrehak wrote and you will feel super easy to get gtest to work.

**Comment by jsrehak** [comment]
`MaterialProtobuf` was merged into `master`
